### ISSUE TITLE
[⛔️ Error Handling]  input CSS 속성 미적용 이슈

### ISSUE THREAD

**Issue by djdu4496** [djdu4496/kokoa-clone-2022#1]
## 어떤 에러인가요?
- input 요소를 클릭 시, border-bottom의 색상이 변하도록 CSS 스타일 코드를 작성했습니다. 
- 하지만, 스타일이 반영되지 않았습니다.
## 에러 메시지
`CSS가 적용되지 않습니다.`
## 에러 핸들링 방법
- CSS 코드 작성 순서에 문제가 있었습니다. 
- 브라우저는 CSS 코드를 위에서 아래로 읽습니다 ⬇
```css
#login-form input:focus {
  border-color: var(--yellow);
`}`

#login-form input:not([type="submit"]) {
  border-bottom: 1px solid rgba(0, 0, 0, 0.2);
  transition: border-color 0.3s ease-in-out;
}
```

🗣 위는 제가 작성한 로그인 form 및 input 관련 CSS 코드입니다. 
🗣 border는 reset.css에 의해 `none`임을 전제합니다.
🗣 `border-color` 스타일이 적용되려면, `border` 스타일이 선행되어야 합니다.
🗣 border-color를 변수 --yellow 색으로 지정한 코드가, border-bottom 코드보다 아래로 가야 해당 코드가 적용된다는 것을 알았습니다.
